SELECT R.ANIMAL_ID
     , R.NAME
FROM (
    SELECT O.ANIMAL_ID
         , O.NAME
         , O.DATETIME - I.DATETIME AS D
    FROM ANIMAL_OUTS O
    LEFT JOIN ANIMAL_INS I ON I.ANIMAL_ID=O.ANIMAL_ID
    WHERE O.ANIMAL_ID IS NOT NULL) R
ORDER BY R.D DESC
LIMIT 2;