SELECT DISTINCT A.CART_ID
FROM CART_PRODUCTS A
LEFT JOIN (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME='MILK'
) M ON M.CART_ID=A.CART_ID
LEFT JOIN (
    SELECT DISTINCT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME='Yogurt'
) Y ON Y.CART_ID=A.CART_ID
WHERE M.CART_ID IS NOT NULL
  AND Y.CART_ID IS NOT NULL;