SELECT H.HOUR
     , CASE
        WHEN R.HOUR IS NULL THEN COUNT(0) - 1
        ELSE COUNT(0)
       END AS COUNT
FROM (
    WITH RECURSIVE NUM AS (SELECT 0 AS HOUR 
                            UNION ALL 
                            SELECT HOUR + 1 FROM NUM WHERE HOUR < 22)
    SELECT * FROM NUM
) H
LEFT JOIN (
    SELECT CAST(DATE_FORMAT(DATETIME,'%H') AS SIGNED) AS HOUR
    FROM ANIMAL_OUTS
) R ON R.HOUR=H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR;
