SELECT FLAVOR
FROM (
    SELECT F.FLAVOR as FLAVOR, J.TOTAL_ORDER + F.TOTAL_ORDER as TOTAL_ORDER
    FROM FIRST_HALF F 
    LEFT JOIN (
        SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) J 
    ON J.FLAVOR = F.FLAVOR
) A
ORDER BY A.TOTAL_ORDER DESC
LIMIT 3