SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM (
        SELECT HOST_ID, COUNT(0) AS CNT
        FROM PLACES
        GROUP BY HOST_ID
    ) R
    WHERE R.CNT > 1
)
GROUP BY ID